export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


// export const HOSPITAL_AUTH_START = 'HOSPITAL_AUTH_START';
// export const HOSPITAL_AUTH_SUCCESS = 'HOSPITAL_AUTH_SUCCESS';
// export const HOSPITAL_AUTH_FAIL = 'HOSPITAL_AUTH_FAIL';
// export const HOSPITAL_AUTH_LOGOUT = 'HOSPITAL_AUTH_LOGOUT';
